package AppMusic;

public class IdealMusic extends javax.swing.JFrame {

    int som = 0;

    public IdealMusic() {
        initComponents();
        setLocationRelativeTo(null);
        openCard("panelMusic");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupAdmSearch = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        panelMusic = new javax.swing.JPanel();
        scrollListMusic = new javax.swing.JScrollPane();
        listMusic = new javax.swing.JList<>();
        btnMusicNacional = new javax.swing.JButton();
        btnMusicInternacional = new javax.swing.JButton();
        labelMusic1 = new javax.swing.JLabel();
        labelMusic2 = new javax.swing.JLabel();
        boxMusicArtist = new javax.swing.JComboBox<>();
        panelUsers = new javax.swing.JPanel();
        panelAdmMain = new javax.swing.JPanel();
        labelAdm2 = new javax.swing.JLabel();
        btnCreateAdm = new javax.swing.JButton();
        btnCreateMusic = new javax.swing.JButton();
        txtAdmSearch = new javax.swing.JTextField();
        scrollAdmList = new javax.swing.JScrollPane();
        listAdmSearch = new javax.swing.JList<>();
        labelAdm3 = new javax.swing.JLabel();
        checkboxAdmMusic = new javax.swing.JCheckBox();
        checkBoxAdmArtist = new javax.swing.JCheckBox();
        btnAdmSearch = new javax.swing.JButton();
        btnAdmCreateAvatar = new javax.swing.JButton();
        panelUserMain = new javax.swing.JPanel();
        labelUserAvatar = new javax.swing.JLabel();
        btnUserUpdateAvatar = new javax.swing.JButton();
        btnUserUpdatePassword = new javax.swing.JButton();
        btnUserEdit = new javax.swing.JButton();
        btnUserSave = new javax.swing.JButton();
        labelUser1 = new javax.swing.JLabel();
        labelUser2 = new javax.swing.JLabel();
        labelUser3 = new javax.swing.JLabel();
        btnUserRefresh = new javax.swing.JButton();
        txtUserEmail = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        btnUserCreatePlaylist = new javax.swing.JButton();
        panelFavorite = new javax.swing.JPanel();
        scrollFavorite1 = new javax.swing.JScrollPane();
        listFavoritePlaylist = new javax.swing.JList<>();
        scrollFavorite2 = new javax.swing.JScrollPane();
        listFavoriteMusic = new javax.swing.JList<>();
        labelFavorite1 = new javax.swing.JLabel();
        btnFavoriteRemovePlaylist = new javax.swing.JButton();
        btnFavoriteRemoveMusic = new javax.swing.JButton();
        labelFavorite2 = new javax.swing.JLabel();
        panelPlaylist = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        panelPlayer = new javax.swing.JPanel();
        labelPlayerImage = new javax.swing.JLabel();
        labelPLayerMusic = new javax.swing.JLabel();
        labelPlayerArtist = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelPlayerTimeDuraction = new javax.swing.JLabel();
        labelPlayerTime = new javax.swing.JLabel();
        sliderPlayerMusic = new javax.swing.JSlider();
        btnPlayerVolume = new javax.swing.JButton();
        btnPlayerNext = new javax.swing.JButton();
        btnPlayerControl = new javax.swing.JButton();
        btnPlayerBack = new javax.swing.JButton();
        btnPlayerLike = new javax.swing.JButton();
        sliderPlayerVolume = new javax.swing.JSlider();
        panelMenu = new javax.swing.JPanel();
        labelMenuLogo = new javax.swing.JLabel();
        btnMenuMusic = new javax.swing.JButton();
        btnMenuPlaylist = new javax.swing.JButton();
        btnMenuFavorite = new javax.swing.JButton();
        btnMenuUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ideal Music");
        setMinimumSize(new java.awt.Dimension(1280, 640));
        setName("frame"); // NOI18N

        panelMain.setLayout(new java.awt.CardLayout());

        panelMusic.setBackground(new java.awt.Color(0, 71, 171));

        listMusic.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        listMusic.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listMusic.setAlignmentX(0.0F);
        listMusic.setAlignmentY(0.0F);
        listMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scrollListMusic.setViewportView(listMusic);

        btnMusicNacional.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnMusicNacional.setText("Nacional");
        btnMusicNacional.setAlignmentY(0.0F);
        btnMusicNacional.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMusicNacional.setFocusable(false);
        btnMusicNacional.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMusicNacional.setMaximumSize(new java.awt.Dimension(150, 30));
        btnMusicNacional.setMinimumSize(new java.awt.Dimension(120, 30));
        btnMusicNacional.setPreferredSize(new java.awt.Dimension(120, 30));

        btnMusicInternacional.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnMusicInternacional.setText("Internacional");
        btnMusicInternacional.setAlignmentY(0.0F);
        btnMusicInternacional.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMusicInternacional.setFocusable(false);
        btnMusicInternacional.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMusicInternacional.setMaximumSize(new java.awt.Dimension(150, 30));
        btnMusicInternacional.setMinimumSize(new java.awt.Dimension(120, 30));
        btnMusicInternacional.setPreferredSize(new java.awt.Dimension(120, 30));

        labelMusic1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        labelMusic1.setForeground(new java.awt.Color(255, 255, 255));
        labelMusic1.setText("Pesquisar por categoria:");

        labelMusic2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        labelMusic2.setForeground(new java.awt.Color(255, 255, 255));
        labelMusic2.setText("Filtrar por artistas:");

        boxMusicArtist.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        boxMusicArtist.setMaximumRowCount(30);
        boxMusicArtist.setAlignmentX(0.0F);
        boxMusicArtist.setAlignmentY(0.0F);
        boxMusicArtist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boxMusicArtist.setFocusable(false);

        javax.swing.GroupLayout panelMusicLayout = new javax.swing.GroupLayout(panelMusic);
        panelMusic.setLayout(panelMusicLayout);
        panelMusicLayout.setHorizontalGroup(
            panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMusicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollListMusic, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMusicLayout.createSequentialGroup()
                        .addComponent(labelMusic2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxMusicArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                        .addComponent(labelMusic1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMusicInternacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMusicNacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelMusicLayout.setVerticalGroup(
            panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMusicLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMusicNacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMusicInternacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelMusic1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelMusic2)
                        .addComponent(boxMusicArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(scrollListMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelMain.add(panelMusic, "panelMusic");

        panelAdmMain.setBackground(new java.awt.Color(0, 71, 171));
        panelAdmMain.setAlignmentX(0.0F);
        panelAdmMain.setAlignmentY(0.0F);
        panelAdmMain.setMinimumSize(new java.awt.Dimension(580, 356));
        panelAdmMain.setPreferredSize(new java.awt.Dimension(580, 356));

        labelAdm2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        labelAdm2.setForeground(new java.awt.Color(255, 255, 255));
        labelAdm2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdm2.setText("Painel de Cadastro:");
        labelAdm2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCreateAdm.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnCreateAdm.setText("Cadastrar Adiministrador");
        btnCreateAdm.setAlignmentY(0.0F);
        btnCreateAdm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateAdm.setFocusable(false);
        btnCreateAdm.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCreateAdm.setMaximumSize(new java.awt.Dimension(250, 30));
        btnCreateAdm.setMinimumSize(new java.awt.Dimension(230, 30));
        btnCreateAdm.setPreferredSize(new java.awt.Dimension(230, 30));
        btnCreateAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAdmActionPerformed(evt);
            }
        });

        btnCreateMusic.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnCreateMusic.setText("Cadastrar Música");
        btnCreateMusic.setAlignmentY(0.0F);
        btnCreateMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateMusic.setFocusable(false);
        btnCreateMusic.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCreateMusic.setMaximumSize(new java.awt.Dimension(250, 30));
        btnCreateMusic.setMinimumSize(new java.awt.Dimension(230, 30));
        btnCreateMusic.setPreferredSize(new java.awt.Dimension(230, 30));

        txtAdmSearch.setAlignmentX(0.0F);
        txtAdmSearch.setAlignmentY(0.0F);
        txtAdmSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAdmSearch.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtAdmSearch.setMinimumSize(new java.awt.Dimension(3, 30));
        txtAdmSearch.setPreferredSize(new java.awt.Dimension(3, 30));

        listAdmSearch.setAlignmentX(0.0F);
        listAdmSearch.setAlignmentY(0.0F);
        scrollAdmList.setViewportView(listAdmSearch);

        labelAdm3.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        labelAdm3.setForeground(new java.awt.Color(255, 255, 255));
        labelAdm3.setText("Digite um nome para pesquisa:");

        checkboxAdmMusic.setBackground(new java.awt.Color(0, 71, 171));
        btnGroupAdmSearch.add(checkboxAdmMusic);
        checkboxAdmMusic.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        checkboxAdmMusic.setForeground(new java.awt.Color(255, 255, 255));
        checkboxAdmMusic.setText("Música");
        checkboxAdmMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        checkBoxAdmArtist.setBackground(new java.awt.Color(0, 71, 171));
        btnGroupAdmSearch.add(checkBoxAdmArtist);
        checkBoxAdmArtist.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        checkBoxAdmArtist.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxAdmArtist.setText("Artista");

        btnAdmSearch.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnAdmSearch.setText("Pesquisar");
        btnAdmSearch.setAlignmentY(0.0F);
        btnAdmSearch.setFocusable(false);
        btnAdmSearch.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdmSearch.setMaximumSize(new java.awt.Dimension(62, 30));
        btnAdmSearch.setMinimumSize(new java.awt.Dimension(62, 30));
        btnAdmSearch.setPreferredSize(new java.awt.Dimension(62, 30));

        btnAdmCreateAvatar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnAdmCreateAvatar.setText("Cadastrar Avatar");
        btnAdmCreateAvatar.setAlignmentY(0.0F);
        btnAdmCreateAvatar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmCreateAvatar.setFocusable(false);
        btnAdmCreateAvatar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdmCreateAvatar.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAdmCreateAvatar.setMinimumSize(new java.awt.Dimension(230, 30));
        btnAdmCreateAvatar.setPreferredSize(new java.awt.Dimension(230, 30));

        javax.swing.GroupLayout panelAdmMainLayout = new javax.swing.GroupLayout(panelAdmMain);
        panelAdmMain.setLayout(panelAdmMainLayout);
        panelAdmMainLayout.setHorizontalGroup(
            panelAdmMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdmMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdmMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAdmSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAdm3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addGroup(panelAdmMainLayout.createSequentialGroup()
                        .addComponent(checkboxAdmMusic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkBoxAdmArtist))
                    .addComponent(btnAdmSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollAdmList))
                .addGap(41, 41, 41)
                .addGroup(panelAdmMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCreateAdm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateMusic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdmCreateAvatar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAdm2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        panelAdmMainLayout.setVerticalGroup(
            panelAdmMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdmMainLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelAdmMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdmMainLayout.createSequentialGroup()
                        .addComponent(labelAdm3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAdmSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAdmMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkboxAdmMusic)
                            .addComponent(checkBoxAdmArtist))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdmSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scrollAdmList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdmMainLayout.createSequentialGroup()
                        .addComponent(labelAdm2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCreateAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCreateMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdmCreateAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelUserMain.setBackground(new java.awt.Color(0, 71, 171));
        panelUserMain.setMinimumSize(new java.awt.Dimension(400, 489));
        panelUserMain.setPreferredSize(new java.awt.Dimension(400, 489));

        labelUserAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/avatar/default.png"))); // NOI18N

        btnUserUpdateAvatar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnUserUpdateAvatar.setAlignmentY(0.0F);
        btnUserUpdateAvatar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserUpdateAvatar.setFocusable(false);
        btnUserUpdateAvatar.setLabel("Alterar avatar");
        btnUserUpdateAvatar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnUserUpdateAvatar.setMaximumSize(new java.awt.Dimension(150, 30));
        btnUserUpdateAvatar.setMinimumSize(new java.awt.Dimension(130, 30));
        btnUserUpdateAvatar.setPreferredSize(new java.awt.Dimension(130, 30));

        btnUserUpdatePassword.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnUserUpdatePassword.setText("Alterar Senha");
        btnUserUpdatePassword.setAlignmentY(0.0F);
        btnUserUpdatePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserUpdatePassword.setFocusable(false);
        btnUserUpdatePassword.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnUserUpdatePassword.setMaximumSize(new java.awt.Dimension(150, 30));
        btnUserUpdatePassword.setMinimumSize(new java.awt.Dimension(130, 30));
        btnUserUpdatePassword.setPreferredSize(new java.awt.Dimension(130, 30));

        btnUserEdit.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnUserEdit.setText("Editar");
        btnUserEdit.setAlignmentY(0.0F);
        btnUserEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserEdit.setFocusable(false);
        btnUserEdit.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnUserEdit.setMaximumSize(new java.awt.Dimension(75, 30));
        btnUserEdit.setMinimumSize(new java.awt.Dimension(75, 30));
        btnUserEdit.setPreferredSize(new java.awt.Dimension(75, 30));

        btnUserSave.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnUserSave.setText("Salvar");
        btnUserSave.setAlignmentY(0.0F);
        btnUserSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserSave.setFocusable(false);

        labelUser1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        labelUser1.setForeground(new java.awt.Color(255, 255, 255));
        labelUser1.setText("Nome:");

        labelUser2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        labelUser2.setForeground(new java.awt.Color(255, 255, 255));
        labelUser2.setText("E-mail:");

        labelUser3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        labelUser3.setForeground(new java.awt.Color(255, 255, 255));
        labelUser3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUser3.setText("Perfil do usuário:");

        btnUserRefresh.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnUserRefresh.setText("Restaurar");
        btnUserRefresh.setAlignmentY(0.0F);
        btnUserRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserRefresh.setFocusable(false);
        btnUserRefresh.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnUserRefresh.setMaximumSize(new java.awt.Dimension(100, 30));
        btnUserRefresh.setMinimumSize(new java.awt.Dimension(100, 30));
        btnUserRefresh.setPreferredSize(new java.awt.Dimension(100, 30));

        txtUserEmail.setAlignmentX(0.0F);
        txtUserEmail.setAlignmentY(0.0F);
        txtUserEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserEmail.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtUserEmail.setMinimumSize(new java.awt.Dimension(230, 30));
        txtUserEmail.setPreferredSize(new java.awt.Dimension(230, 30));

        txtUserName.setAlignmentX(0.0F);
        txtUserName.setAlignmentY(0.0F);
        txtUserName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserName.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtUserName.setMinimumSize(new java.awt.Dimension(230, 30));
        txtUserName.setPreferredSize(new java.awt.Dimension(230, 30));

        btnUserCreatePlaylist.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnUserCreatePlaylist.setText("Criar Playlist");
        btnUserCreatePlaylist.setAlignmentY(0.0F);
        btnUserCreatePlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserCreatePlaylist.setFocusable(false);
        btnUserCreatePlaylist.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnUserCreatePlaylist.setMaximumSize(new java.awt.Dimension(250, 30));
        btnUserCreatePlaylist.setMinimumSize(new java.awt.Dimension(230, 30));
        btnUserCreatePlaylist.setPreferredSize(new java.awt.Dimension(230, 30));
        btnUserCreatePlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserCreatePlaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUserMainLayout = new javax.swing.GroupLayout(panelUserMain);
        panelUserMain.setLayout(panelUserMainLayout);
        panelUserMainLayout.setHorizontalGroup(
            panelUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserMainLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(panelUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUserMainLayout.createSequentialGroup()
                        .addGroup(panelUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUser1)
                            .addComponent(labelUser2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelUserMainLayout.createSequentialGroup()
                                .addComponent(btnUserRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUserMainLayout.createSequentialGroup()
                                .addComponent(labelUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUserSave))
                            .addComponent(txtUserEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnUserCreatePlaylist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnUserUpdateAvatar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUserUpdatePassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelUserMainLayout.createSequentialGroup()
                            .addComponent(labelUserAvatar)
                            .addGap(16, 16, 16))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelUserMainLayout.setVerticalGroup(
            panelUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserMainLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(panelUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUser3)
                    .addComponent(btnUserSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUser1)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUser2)
                    .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(labelUserAvatar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUserUpdateAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUserUpdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUserCreatePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout panelUsersLayout = new javax.swing.GroupLayout(panelUsers);
        panelUsers.setLayout(panelUsersLayout);
        panelUsersLayout.setHorizontalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersLayout.createSequentialGroup()
                .addComponent(panelUserMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelAdmMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsersLayout.setVerticalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUserMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelAdmMain, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        panelMain.add(panelUsers, "panelUsers");

        panelFavorite.setBackground(new java.awt.Color(0, 71, 171));

        listFavoritePlaylist.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        listFavoritePlaylist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listFavoritePlaylist.setAlignmentX(0.0F);
        listFavoritePlaylist.setAlignmentY(0.0F);
        listFavoritePlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scrollFavorite1.setViewportView(listFavoritePlaylist);

        listFavoriteMusic.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        listFavoriteMusic.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listFavoriteMusic.setAlignmentX(0.0F);
        listFavoriteMusic.setAlignmentY(0.0F);
        listFavoriteMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scrollFavorite2.setViewportView(listFavoriteMusic);

        labelFavorite1.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        labelFavorite1.setForeground(new java.awt.Color(255, 255, 255));
        labelFavorite1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFavorite1.setText("Músicas Favoritadas");
        labelFavorite1.setAlignmentY(0.0F);

        btnFavoriteRemovePlaylist.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnFavoriteRemovePlaylist.setText("Remover Playlist de favoritos");
        btnFavoriteRemovePlaylist.setAlignmentY(0.0F);
        btnFavoriteRemovePlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFavoriteRemovePlaylist.setFocusable(false);
        btnFavoriteRemovePlaylist.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnFavoriteRemovePlaylist.setMaximumSize(new java.awt.Dimension(200, 30));
        btnFavoriteRemovePlaylist.setMinimumSize(new java.awt.Dimension(200, 30));
        btnFavoriteRemovePlaylist.setPreferredSize(new java.awt.Dimension(200, 30));

        btnFavoriteRemoveMusic.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnFavoriteRemoveMusic.setText("Remover Música de favoritos");
        btnFavoriteRemoveMusic.setAlignmentY(0.0F);
        btnFavoriteRemoveMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFavoriteRemoveMusic.setFocusable(false);
        btnFavoriteRemoveMusic.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnFavoriteRemoveMusic.setMaximumSize(new java.awt.Dimension(200, 30));
        btnFavoriteRemoveMusic.setMinimumSize(new java.awt.Dimension(200, 30));
        btnFavoriteRemoveMusic.setPreferredSize(new java.awt.Dimension(200, 30));

        labelFavorite2.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        labelFavorite2.setForeground(new java.awt.Color(255, 255, 255));
        labelFavorite2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFavorite2.setText("Playlists Favoritadas");

        javax.swing.GroupLayout panelFavoriteLayout = new javax.swing.GroupLayout(panelFavorite);
        panelFavorite.setLayout(panelFavoriteLayout);
        panelFavoriteLayout.setHorizontalGroup(
            panelFavoriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFavoriteLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(panelFavoriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFavoriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelFavorite1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrollFavorite2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                    .addComponent(btnFavoriteRemoveMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelFavoriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFavoriteRemovePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollFavorite1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(labelFavorite2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelFavoriteLayout.setVerticalGroup(
            panelFavoriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFavoriteLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelFavoriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFavorite1)
                    .addComponent(labelFavorite2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFavoriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollFavorite1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(scrollFavorite2))
                .addGap(18, 18, 18)
                .addGroup(panelFavoriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFavoriteRemovePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFavoriteRemoveMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        panelMain.add(panelFavorite, "panelFavorite");

        panelPlaylist.setBackground(new java.awt.Color(0, 71, 171));
        panelPlaylist.setAlignmentX(0.0F);
        panelPlaylist.setAlignmentY(0.0F);

        jList1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setAlignmentX(0.0F);
        jList1.setAlignmentY(0.0F);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Procurar playlists em destaque:");

        javax.swing.GroupLayout panelPlaylistLayout = new javax.swing.GroupLayout(panelPlaylist);
        panelPlaylist.setLayout(panelPlaylistLayout);
        panelPlaylistLayout.setHorizontalGroup(
            panelPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlaylistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                    .addGroup(panelPlaylistLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPlaylistLayout.setVerticalGroup(
            panelPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlaylistLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMain.add(panelPlaylist, "panelPlaylist");

        panelPlayer.setBackground(new java.awt.Color(179, 7, 83));
        panelPlayer.setMaximumSize(new java.awt.Dimension(32767, 200));
        panelPlayer.setMinimumSize(new java.awt.Dimension(900, 150));
        panelPlayer.setPreferredSize(new java.awt.Dimension(991, 150));

        labelPlayerImage.setBackground(new java.awt.Color(255, 255, 255));
        labelPlayerImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPlayerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/default.png"))); // NOI18N
        labelPlayerImage.setAlignmentY(0.0F);
        labelPlayerImage.setMaximumSize(new java.awt.Dimension(250, 250));
        labelPlayerImage.setMinimumSize(new java.awt.Dimension(150, 150));
        labelPlayerImage.setPreferredSize(new java.awt.Dimension(150, 150));

        labelPLayerMusic.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        labelPLayerMusic.setForeground(new java.awt.Color(255, 255, 255));
        labelPLayerMusic.setText("Nome da música");

        labelPlayerArtist.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        labelPlayerArtist.setForeground(new java.awt.Color(255, 255, 255));
        labelPlayerArtist.setText("Artista/Banda");

        jPanel1.setBackground(new java.awt.Color(179, 7, 83));

        labelPlayerTimeDuraction.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        labelPlayerTimeDuraction.setForeground(new java.awt.Color(255, 255, 255));
        labelPlayerTimeDuraction.setText("00:00");

        labelPlayerTime.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        labelPlayerTime.setForeground(new java.awt.Color(255, 255, 255));
        labelPlayerTime.setText("00:00");

        sliderPlayerMusic.setBackground(new java.awt.Color(179, 7, 83));
        sliderPlayerMusic.setForeground(new java.awt.Color(255, 255, 255));
        sliderPlayerMusic.setValue(0);
        sliderPlayerMusic.setAlignmentX(0.0F);
        sliderPlayerMusic.setAlignmentY(0.0F);
        sliderPlayerMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sliderPlayerMusic.setFocusable(false);
        sliderPlayerMusic.setMaximumSize(new java.awt.Dimension(32767, 18));
        sliderPlayerMusic.setMinimumSize(new java.awt.Dimension(400, 18));
        sliderPlayerMusic.setPreferredSize(new java.awt.Dimension(400, 18));

        btnPlayerVolume.setBackground(new java.awt.Color(179, 7, 83));
        btnPlayerVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/som.png"))); // NOI18N
        btnPlayerVolume.setAlignmentY(0.0F);
        btnPlayerVolume.setBorder(null);
        btnPlayerVolume.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlayerVolume.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPlayerVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerVolumeActionPerformed(evt);
            }
        });

        btnPlayerNext.setBackground(new java.awt.Color(179, 7, 83));
        btnPlayerNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/next.png"))); // NOI18N
        btnPlayerNext.setAlignmentY(0.0F);
        btnPlayerNext.setBorder(null);
        btnPlayerNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlayerNext.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnPlayerControl.setBackground(new java.awt.Color(179, 7, 83));
        btnPlayerControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/play.png"))); // NOI18N
        btnPlayerControl.setAlignmentY(0.0F);
        btnPlayerControl.setBorder(null);
        btnPlayerControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlayerControl.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnPlayerBack.setBackground(new java.awt.Color(179, 7, 83));
        btnPlayerBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/back.png"))); // NOI18N
        btnPlayerBack.setAlignmentY(0.0F);
        btnPlayerBack.setBorder(null);
        btnPlayerBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlayerBack.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnPlayerLike.setBackground(new java.awt.Color(179, 7, 83));
        btnPlayerLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/like.png"))); // NOI18N
        btnPlayerLike.setAlignmentY(0.0F);
        btnPlayerLike.setBorder(null);
        btnPlayerLike.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlayerLike.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPlayerTimeDuraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderPlayerMusic, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPlayerTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPlayerLike)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPlayerBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnPlayerControl)
                        .addGap(18, 18, 18)
                        .addComponent(btnPlayerNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPlayerVolume)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sliderPlayerMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPlayerTimeDuraction, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPlayerTime, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayerVolume)
                    .addComponent(btnPlayerLike)
                    .addComponent(btnPlayerControl)
                    .addComponent(btnPlayerNext)
                    .addComponent(btnPlayerBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sliderPlayerVolume.setBackground(new java.awt.Color(179, 7, 83));
        sliderPlayerVolume.setForeground(new java.awt.Color(179, 7, 83));
        sliderPlayerVolume.setMaximum(0);
        sliderPlayerVolume.setMinimum(-80);
        sliderPlayerVolume.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderPlayerVolume.setValue(0);
        sliderPlayerVolume.setMinimumSize(new java.awt.Dimension(20, 130));
        sliderPlayerVolume.setPreferredSize(new java.awt.Dimension(20, 130));

        javax.swing.GroupLayout panelPlayerLayout = new javax.swing.GroupLayout(panelPlayer);
        panelPlayer.setLayout(panelPlayerLayout);
        panelPlayerLayout.setHorizontalGroup(
            panelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayerLayout.createSequentialGroup()
                .addComponent(labelPlayerImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPLayerMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPlayerArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderPlayerVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPlayerLayout.setVerticalGroup(
            panelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelPlayerImage, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlayerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPlayerLayout.createSequentialGroup()
                        .addComponent(labelPLayerMusic)
                        .addGap(0, 0, 0)
                        .addComponent(labelPlayerArtist)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlayerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sliderPlayerVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu.setBackground(new java.awt.Color(179, 7, 83));
        panelMenu.setAlignmentX(0.0F);
        panelMenu.setAlignmentY(0.0F);
        panelMenu.setMinimumSize(new java.awt.Dimension(300, 640));
        panelMenu.setPreferredSize(new java.awt.Dimension(300, 640));

        labelMenuLogo.setBackground(new java.awt.Color(255, 255, 255));
        labelMenuLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/logo.png"))); // NOI18N
        labelMenuLogo.setAlignmentY(0.0F);
        labelMenuLogo.setMaximumSize(new java.awt.Dimension(300, 240));
        labelMenuLogo.setMinimumSize(new java.awt.Dimension(300, 180));
        labelMenuLogo.setPreferredSize(new java.awt.Dimension(300, 180));

        btnMenuMusic.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuMusic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/textMusic.png"))); // NOI18N
        btnMenuMusic.setAlignmentY(0.0F);
        btnMenuMusic.setBorder(null);
        btnMenuMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuMusic.setFocusable(false);
        btnMenuMusic.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMenuMusic.setMaximumSize(new java.awt.Dimension(300, 1000000));
        btnMenuMusic.setMinimumSize(new java.awt.Dimension(300, 120));
        btnMenuMusic.setPreferredSize(new java.awt.Dimension(300, 115));
        btnMenuMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMusicActionPerformed(evt);
            }
        });

        btnMenuPlaylist.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/textPlaylists.png"))); // NOI18N
        btnMenuPlaylist.setAlignmentY(0.0F);
        btnMenuPlaylist.setBorder(null);
        btnMenuPlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuPlaylist.setFocusable(false);
        btnMenuPlaylist.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMenuPlaylist.setMaximumSize(new java.awt.Dimension(300, 1000000));
        btnMenuPlaylist.setMinimumSize(new java.awt.Dimension(300, 120));
        btnMenuPlaylist.setPreferredSize(new java.awt.Dimension(300, 115));
        btnMenuPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPlaylistActionPerformed(evt);
            }
        });

        btnMenuFavorite.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuFavorite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/textFavorite.png"))); // NOI18N
        btnMenuFavorite.setAlignmentY(0.0F);
        btnMenuFavorite.setBorder(null);
        btnMenuFavorite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuFavorite.setFocusable(false);
        btnMenuFavorite.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMenuFavorite.setMaximumSize(new java.awt.Dimension(300, 1000000));
        btnMenuFavorite.setMinimumSize(new java.awt.Dimension(300, 120));
        btnMenuFavorite.setPreferredSize(new java.awt.Dimension(300, 115));
        btnMenuFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuFavoriteActionPerformed(evt);
            }
        });

        btnMenuUser.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/textUser.png"))); // NOI18N
        btnMenuUser.setAlignmentY(0.0F);
        btnMenuUser.setBorder(null);
        btnMenuUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuUser.setFocusable(false);
        btnMenuUser.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMenuUser.setMaximumSize(new java.awt.Dimension(300, 1000000));
        btnMenuUser.setMinimumSize(new java.awt.Dimension(300, 120));
        btnMenuUser.setPreferredSize(new java.awt.Dimension(300, 115));
        btnMenuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMenuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnMenuPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMenuFavorite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMenuUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelMenuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMenuMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnMenuPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnMenuFavorite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnMenuUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUserActionPerformed
        openCard("panelUsers");
    }//GEN-LAST:event_btnMenuUserActionPerformed

    private void btnMenuFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuFavoriteActionPerformed
        openCard("panelFavorite");
    }//GEN-LAST:event_btnMenuFavoriteActionPerformed

    private void btnCreateAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateAdmActionPerformed

    private void btnMenuMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMusicActionPerformed
        openCard("panelMusic");
    }//GEN-LAST:event_btnMenuMusicActionPerformed

    private void btnMenuPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPlaylistActionPerformed
        openCard("panelPlaylist");
    }//GEN-LAST:event_btnMenuPlaylistActionPerformed

    private void btnUserCreatePlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserCreatePlaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserCreatePlaylistActionPerformed

    private void btnPlayerVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerVolumeActionPerformed
        if (som == 0) {
            btnPlayerVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/mute.png")));
            sliderPlayerVolume.setVisible(false);
            som++;
        } else {
            btnPlayerVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/som.png")));
            sliderPlayerVolume.setVisible(true);
            som = 0;
        }
    }//GEN-LAST:event_btnPlayerVolumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdealMusic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdealMusic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdealMusic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdealMusic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdealMusic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxMusicArtist;
    private javax.swing.JButton btnAdmCreateAvatar;
    private javax.swing.JButton btnAdmSearch;
    private javax.swing.JButton btnCreateAdm;
    private javax.swing.JButton btnCreateMusic;
    private javax.swing.JButton btnFavoriteRemoveMusic;
    private javax.swing.JButton btnFavoriteRemovePlaylist;
    private javax.swing.ButtonGroup btnGroupAdmSearch;
    private javax.swing.JButton btnMenuFavorite;
    private javax.swing.JButton btnMenuMusic;
    private javax.swing.JButton btnMenuPlaylist;
    private javax.swing.JButton btnMenuUser;
    private javax.swing.JButton btnMusicInternacional;
    private javax.swing.JButton btnMusicNacional;
    private javax.swing.JButton btnPlayerBack;
    private javax.swing.JButton btnPlayerControl;
    private javax.swing.JButton btnPlayerLike;
    private javax.swing.JButton btnPlayerNext;
    private javax.swing.JButton btnPlayerVolume;
    private javax.swing.JButton btnUserCreatePlaylist;
    private javax.swing.JButton btnUserEdit;
    private javax.swing.JButton btnUserRefresh;
    private javax.swing.JButton btnUserSave;
    private javax.swing.JButton btnUserUpdateAvatar;
    private javax.swing.JButton btnUserUpdatePassword;
    private javax.swing.JCheckBox checkBoxAdmArtist;
    private javax.swing.JCheckBox checkboxAdmMusic;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAdm2;
    private javax.swing.JLabel labelAdm3;
    private javax.swing.JLabel labelFavorite1;
    private javax.swing.JLabel labelFavorite2;
    private javax.swing.JLabel labelMenuLogo;
    private javax.swing.JLabel labelMusic1;
    private javax.swing.JLabel labelMusic2;
    private javax.swing.JLabel labelPLayerMusic;
    private javax.swing.JLabel labelPlayerArtist;
    private javax.swing.JLabel labelPlayerImage;
    private javax.swing.JLabel labelPlayerTime;
    private javax.swing.JLabel labelPlayerTimeDuraction;
    private javax.swing.JLabel labelUser1;
    private javax.swing.JLabel labelUser2;
    private javax.swing.JLabel labelUser3;
    private javax.swing.JLabel labelUserAvatar;
    private javax.swing.JList<String> listAdmSearch;
    private javax.swing.JList<String> listFavoriteMusic;
    private javax.swing.JList<String> listFavoritePlaylist;
    private javax.swing.JList<String> listMusic;
    private javax.swing.JPanel panelAdmMain;
    private javax.swing.JPanel panelFavorite;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMusic;
    private javax.swing.JPanel panelPlayer;
    private javax.swing.JPanel panelPlaylist;
    private javax.swing.JPanel panelUserMain;
    private javax.swing.JPanel panelUsers;
    private javax.swing.JScrollPane scrollAdmList;
    private javax.swing.JScrollPane scrollFavorite1;
    private javax.swing.JScrollPane scrollFavorite2;
    private javax.swing.JScrollPane scrollListMusic;
    private javax.swing.JSlider sliderPlayerMusic;
    private javax.swing.JSlider sliderPlayerVolume;
    private javax.swing.JTextField txtAdmSearch;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    public void openCard(String cardName) {
        java.awt.CardLayout card = (java.awt.CardLayout) panelMain.getLayout();
        card.show(panelMain, cardName);
    }
}
